name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: based_pg
        ports:
          - 54322:5432

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.14.0"
          rebar3-version: "3"

      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
